channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - cmake
    - gcc
    - gxx
    - ninja
    - eigen
    - shogun-cpp=6.1.4
    - wheel
    - pybind11
    - nlohmann_json
    - pybind11_json
    - pip
    - pip:
        - git+https://github.com/gAldeia/feat.git