name: regression-benchmarks
channels:
    - conda-forge
dependencies:
    - python=3.9.1
    - eigen=3.3.7
    - boost=1.74.0
    - scikit-learn=0.23.2
    - pandas=1.1.*
    - xgboost
    - pip=20.3.3
    - armadillo=9.900.4
    - fmt=7.1.3
    - ceres-solver=2.0.0
    - tbb 
    - pip:
        - DistanceClassifier==0.0.8
        - pmlb
        - ffx==2.0.2
    # - setuptools=45.*
    # - wheel=0.35.*
    # - pip=20.*
    # - pip:
# ellyn=0.1
