name: srbench
channels:
    - conda-forge
dependencies:
    - python #=3.9.1
    - cmake=3.19.1 # operon, feat 
    - eigen=3.3.9 # operon, feat, ellyn
    - boost=1.74.0 # gpgomea, ellyn
    - scikit-learn=0.24.1 
    - pandas #=1.1.*
    - xgboost
    - lightgbm
    - gplearn
    - armadillo=9.900.4 # gpgomea
    #vv operon vv#
    - pybind11=2.6.1 
    - fmt=7.1.3 
    - ceres-solver=2.0.0 
    - tbb-devel=2020.2 
    - openlibm 
    - cxxopts 
    #^^ operon ^^#
    - jupyter
    - pytest
    - matplotlib
    #vv ITEA vv#
    - pkg-config
    - gmp
    - libffi
    - gsl
    - libblas
    - liblapack
    - stack
    #^^ ITEA ^^#
    #vv deep-symbolic-regression vv#
    - tensorflow=1.14 
    - cython
    - numpy
    - numba
    - sympy
    - click
    - mpi4py
    - dataclasses
    #^^ deep-symbolic-regression ^^#
    - pip=20.3.3 
    - pip:
        - DistanceClassifier==0.0.8 # ellyn
        - pmlb==1.0.1.post3
        - ffx==2.0.2 # ffx
        - git+https://github.com/lacava/MCMC-SymReg
