name: PSTree
channels:
    - conda-forge
dependencies:
    - python=3.8
    - scikit-learn
    - pandas 
    - numpy
    - jupyter
    - pytest
    - matplotlib
    - sympy
    - pip
    - gplearn
    - scipy
    - deap
    - PyYAML
    - cython