name: TaylorGP
channels:
    - conda-forge
dependencies:
    - python>=3.6
    - cmake>=3.18
    - scikit-learn>=0.22.1
    - numpy>=1.19.*
    - sympy>=1.7.*
    - pandas>=1.2.*
    - scipy>=1.6.2
    - joblib>=0.13.0
    - cython=0.29.*
    - pip=20.*
    - pandas>=1.2.*
    - pytest>=7.*
    - pyyaml>=5.*
