name: QLattice
channels:
    - conda-forge
dependencies:
    - python=3.8
    - numpy==1.22.3
    - pandas==1.4.2
    - scikit-learn==1.0.2
    - sympy==1.10.1
    - pip
    - pip:
        - pmlb==1.*
        - feyn==3.0.1
