channels:
    - conda-forge
    - defaults
dependencies:
    - cmake
    - gcc
    - gxx
    - ninja
    - eigen
    - pandas
    - scikit-learn
    - shogun-cpp
    - wheel
    - pybind11
    - nlohmann_json
    - pybind11_json
    - pip
    - pip:
        - pmlb
        - git+https://github.com/cavalab/feat.git