channels:
    - conda-forge
dependencies:
    - python=3.*
    - cmake>=3.18
    - ninja
    - eigen>=3.3
    - cython=0.29.*
    - pandas=1.1.*
    # - setuptools=45.*
    - setuptools
    - shogun-cpp=6.1.4
    - wheel=0.35.*
    # - pip=20.*
    - pip
    - pip:
        - eigency==1.77
        - pmlb==1.*
