name: Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    types:
      	- assigned
        - opened
        - edited
        - reopened
        - synchronize
    branches: 
      - master 

env:
  USER: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  APP: srbench

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      TAG: latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.USER }}/${{ env.APP }}:${{ env.TAG }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.USER }}/${{ env.APP }}:${{ env.TAG }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.USER }}/${{ env.APP }}:${{ env.TAG }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
