# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Caches the conda environment
      # - name: Cache conda
      #   uses: actions/cache@v1
      #   env:
      #     # Increase this value to reset cache if environment.yml has not changed
      #     CACHE_NUMBER: 0
      #   with:
      #     path: ~/conda_pkgs_dir
      #     key:
      #       ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
      #       hashFiles('etc/example-environment.yml') }}
      # Sets up the conda environment
      - name: Set up Conda Environment 
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: srbench
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
          conda activate srbench

      - name: Install SR methods
        run: |
            conda info
            bash install.sh

      - name: Test analysis 
        run: |
            conda info 
            # pip install pytest
            cd experiment
            python -m pytest -v test_evaluate_model.py
            python -m pytest -v test_tuned_models.py
